proxy-groups:
  - type: select
    default: reject
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸš« å¹¿å‘Šæ‹¦æˆª
  - type: select
    default: direct
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ  æœ¬åœ°ç½‘ç»œ
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ€ Google
  - type: select
    default: â™»ï¸ ç¾å›½è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ¤– AI
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ® Steam
  - type: select
    default: direct
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ“º BiliBili
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - type: select
    default: direct
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ” Bing
  - type: select
    default: direct
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: â˜ï¸ OneDrive
  - type: select
    default: direct
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: â“‚ï¸ Microsoft
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ“² Telegram
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ“¹ YouTube
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ¤ Twitter
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸµ TikTok
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ¥ NETFLIX
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸ’¶ PayPal
  - type: select
    default: ğŸš€ é»˜è®¤è‡ªåŠ¨
    proxies:
      - ğŸš€ é»˜è®¤è‡ªåŠ¨
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - â™»ï¸ å°æ¹¾è‡ªåŠ¨
      - â™»ï¸ éŸ©å›½è‡ªåŠ¨
      - â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
      - â™»ï¸ ç‹®åŸè‡ªåŠ¨
      - â™»ï¸ ç¾å›½è‡ªåŠ¨
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - direct
      - reject
    name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  - include-all: true
    type: select
    name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    filter: (?i)æ¸¯|hk|hongkong|hong kong
  - include-all: true
    type: select
    name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
    filter: (?i)å°æ¹¾|æ¹¾|tw|taiwan
  - include-all: true
    type: select
    name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    filter: (?i)éŸ©å›½|éŸ©|kr|Korean
  - include-all: true
    type: select
    name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    filter: (?i)æ—¥|æ—¥æœ¬|jp|japan
  - include-all: true
    type: select
    name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
  - include-all: true
    type: select
    name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    filter: (?i)ç¾|ç¾å›½|us|unitedstates|united states
  - include-all: true
    type: select
    name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: ğŸš€ é»˜è®¤è‡ªåŠ¨
    filter: ^(?!.*(ç›´è¿)).*$
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
    filter: (?i)æ¸¯|hk|hongkong|hong kong
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ å°æ¹¾è‡ªåŠ¨
    filter: (?i)å°æ¹¾|æ¹¾|tw|taiwan
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ éŸ©å›½è‡ªåŠ¨
    filter: (?i)éŸ©å›½|éŸ©|kr|Korean
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨
    filter: (?i)æ—¥|æ—¥æœ¬|jp|japan
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ ç‹®åŸè‡ªåŠ¨
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
  - type: url-test
    url: http://www.gstatic.com/generate_204
    include-all: true
    tolerance: 20
    interval: 60
    name: â™»ï¸ ç¾å›½è‡ªåŠ¨
    filter: (?i)ç¾|ç¾å›½|us|unitedstates|united states
rules:
  - RULE-SET,awavenue_ads,ğŸš« å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,lan_ip,ğŸ  æœ¬åœ°ç½‘ç»œ,no-resolve
  - RULE-SET,private_ip,direct,no-resolve
  - RULE-SET,private_domain,direct
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤è‡ªåŠ¨
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,ai,ğŸ¤– AI
  - RULE-SET,cn_steam_domain,direct
  - RULE-SET,steam_domain,ğŸ® Steam
  - RULE-SET,bilibili_domain,ğŸ“º BiliBili
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,bing_domain,ğŸ” Bing
  - RULE-SET,onedrive_domain,â˜ï¸ OneDrive
  - RULE-SET,microsoft_domain,â“‚ï¸ Microsoft
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,twitter_domain,ğŸ¤ Twitter
  - RULE-SET,cn_apple_domain,direct
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,apple_ip,direct,no-resolve
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤è‡ªåŠ¨
  - RULE-SET,cn_domain,direct
  - RULE-SET,cn_ip,direct
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-providers:
  proxylite:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list
  lan_ip:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/zsjsll/proxy-config/refs/heads/self/rules/lan-ip.yaml
  awavenue_ads:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  ai:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs
  youtube_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
  google_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
  github_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
  twitter_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs
  telegram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
  steam_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs
  cn_steam_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs
  netflix_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
  bilibili_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs
  paypal_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs
  onedrive_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs
  bing_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bing.mrs
  microsoft_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
  cn_apple_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
  speedtest_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
  tiktok_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  private_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
  google_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
  netflix_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
  apple_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs
