name: Build and Push Mixed Artifacts

on:
  push:
    branches:
      - self

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_DIR: dist # 变量 1: 产物目录名
      TARGET_BRANCH: dist # 变量 2: 目标分支名

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.10.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.18.2

      - name: Setup cache
        uses: actions/cache@v4.3.0
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Configure Git for Bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check target branch and create
        run: |
          if ! git show-ref --verify --quiet refs/heads/${{ env.TARGET_BRANCH }}; then
          echo "Branch ${{ env.TARGET_BRANCH }} does not exist. Creating it as an orphan branch."

          git checkout --orphan ${{ env.TARGET_BRANCH }}
          git rm -rf .
          git commit --allow-empty -m "Initialize deployment branch"
          git push origin ${{ env.TARGET_BRANCH }}
          git checkout ${{ github.ref_name }}
          fi

      - name: Checkout target branch and clear
        run: |
          rm -rf ${{ env.ARTIFACT_DIR }}
          git worktree prune
          git worktree add ${{ env.ARTIFACT_DIR }} ${{ env.TARGET_BRANCH }}
          cd ${{ env.ARTIFACT_DIR }}
          rm -rf ./*
          cd ..

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Commit and push build artifacts
        run: |

          if [ ! -d "$ARTIFACT_DIR" ]; then
              echo "Error: Build output directory '$ARTIFACT_DIR' not found. Check build step."
              exit 1
          fi

          cd ${{ env.ARTIFACT_DIR }}
          git add -A
          git diff --cached --quiet || git commit -m "Update file from commit ${{ github.sha }} [skip ci]"
          git push origin HEAD:${{ env.TARGET_BRANCH }}
